# Generated by Django 4.2.16 on 2024-11-15 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogAuthorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='博主姓名')),
                ('age', models.IntegerField(verbose_name='博主年龄')),
                ('desc', models.TextField(verbose_name='博主简介')),
            ],
        ),
        migrations.CreateModel(
            name='BlogCommentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='评论者姓名')),
                ('pub_datetime', models.DateTimeField(verbose_name='评论时间')),
                ('comment', models.TextField(verbose_name='评论内容')),
            ],
        ),
        migrations.CreateModel(
            name='BlogContentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='博文名称')),
                ('upload_date', models.DateField(verbose_name='上传日期')),
                ('content', models.TextField(verbose_name='博文内容')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blogauthormodel', verbose_name='博文作者')),
            ],
        ),
    ]
