# Generated by Django 4.2.16 on 2024-11-15 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogauthormodel',
            options={'verbose_name': '博主', 'verbose_name_plural': '博主列表'},
        ),
    ]
