# Generated by Django 4.2.16 on 2024-11-15 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blogauthormodel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcontentmodel',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogcontent', to='blog.blogauthormodel', verbose_name='博文作者'),
        ),
    ]
