# Generated by Django 4.2.16 on 2024-11-13 02:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.text
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='名')),
                ('last_name', models.CharField(max_length=100, verbose_name='姓')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='出生日期')),
                ('date_of_death', models.DateField(blank=True, null=True, verbose_name='去世日期')),
                ('gender', models.CharField(choices=[('M', '男'), ('F', '女')], default='M', max_length=1, verbose_name='性别')),
            ],
            options={
                'verbose_name': '书籍作者',
                'verbose_name_plural': '书籍作者表',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='书籍标题')),
                ('summary', models.TextField(max_length=1000, verbose_name='书籍简介')),
                ('isbn', models.CharField(help_text='13位<a href="https://www.isbn-international.org/content/what-isbn">ISBN码</a>', max_length=13, unique=True, verbose_name='书籍ISBN')),
            ],
            options={
                'verbose_name': '书籍',
                'verbose_name_plural': '书籍表',
                'ordering': ['title', 'author'],
            },
        ),
        migrations.CreateModel(
            name='BookInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='唯一ID用于表示每本书', primary_key=True, serialize=False, verbose_name='书籍编号')),
                ('imprint', models.CharField(max_length=200, verbose_name='书籍Imprint')),
                ('due_back', models.DateField(blank=True, null=True, verbose_name='归还日期')),
                ('status', models.CharField(blank=True, choices=[('m', '维护'), ('o', '借出'), ('a', '空闲'), ('r', '预定')], default='m', max_length=1, verbose_name='书籍状态')),
            ],
            options={
                'verbose_name': '书籍状态',
                'verbose_name_plural': '书籍状态表',
                'ordering': ['due_back'],
                'permissions': (('can_mark_returned', '归还图书'),),
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='输入一个书籍类型，例如科幻小说、网络小说', max_length=100, unique=True, verbose_name='类型名称')),
            ],
            options={
                'verbose_name': '书籍类型',
                'verbose_name_plural': '书籍类型表',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='输入一个书籍语言，例如中文、日语', max_length=200, unique=True, verbose_name='语言名称')),
            ],
            options={
                'verbose_name': '书籍语言',
                'verbose_name_plural': '书籍语言表',
            },
        ),
        migrations.AddConstraint(
            model_name='language',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='语言名称唯一约束', violation_error_message='语言已存在（不区分大小写）'),
        ),
        migrations.AddConstraint(
            model_name='genre',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='类型名称唯一约束', violation_error_message='类型已存在（不区分大小写）'),
        ),
        migrations.AddField(
            model_name='bookinstance',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalog.book', verbose_name='书籍'),
        ),
        migrations.AddField(
            model_name='bookinstance',
            name='borrower',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='借阅者'),
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalog.author', verbose_name='书籍作者'),
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(help_text='为书籍选择一个类型', to='catalog.genre', verbose_name='书籍类型'),
        ),
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.language', verbose_name='书籍语言'),
        ),
    ]
