# Generated by Django 4.2.16 on 2024-11-14 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': (('can_mark_returned', 'return_book'),), 'verbose_name': '书籍状态', 'verbose_name_plural': '书籍状态表'},
        ),
    ]
